import type { CurveSample, EditableNode, Point } from "./types";
import { simplifyRDP } from "./simplify";
import { autoHandles, buildCurveFromNodes, insertNodeAt, removeNodeAt, nearestSegmentIndex, setNodeCorner } from "./spline";
import { buildStemPolygon, polygonToPath } from "./stem";
import { placeBrush, type BrushOptions, type BrushPlacement } from "./brush";

export interface VineParams {
  stemWidth: number;
  brush: BrushOptions;
  /** Faux pour une branche : sa racine ne s'amincit pas, elle reste pleine largeur pour se fondre dans sa tige parente. */
  taperStart?: boolean;
  taperEnd?: boolean;
  /** Vrai pour une liane née de "Volutes auto" plutôt que tracée à la main — porté ici (plutôt qu'un
      état ui/main.ts seulement) pour survivre à la sérialisation (undo/redo, rechargement depuis
      localStorage), afin qu'un lot auto-généré reste reconnaissable même après ces opérations. */
  autoGenerated?: boolean;
}

export interface VineRenderData {
  curve: CurveSample[];
  /** Polygone brut de la tige (avant sérialisation), réutilisé tel quel pour la fusion à une jonction — voir junction.ts. */
  stemPolygon: Point[];
  stemPathD: string;
  leaves: BrushPlacement[];
}

/** Simplifie un tracé brut à main levée en nœuds éditables (poignées auto-lissées). */
export function nodesFromStroke(rawPoints: Point[], simplifyEpsilon: number): EditableNode[] {
  const controlPoints = simplifyRDP(rawPoints, simplifyEpsilon);
  return autoHandles(controlPoints);
}

/** Convertit une suite de points posés un par un (mode "Points") en nœuds éditables. */
export function nodesFromClicks(points: Point[]): EditableNode[] {
  return autoHandles(points);
}

/** Ajoute/retire un nœud, ou bascule un nœud lisse/coin, sur une liane existante — voir spline.ts. */
export { insertNodeAt, removeNodeAt, nearestSegmentIndex, setNodeCorner };

/** Recalcule la tige et les feuilles à partir de l'état courant des nœuds — appelé à la création comme à chaque édition. */
export function regenerateVine(nodes: EditableNode[], params: VineParams): VineRenderData {
  const curve = buildCurveFromNodes(nodes);
  const taper = { taperStart: params.taperStart, taperEnd: params.taperEnd };
  const stemPolygon = buildStemPolygon(curve, params.stemWidth, taper);
  return {
    curve,
    stemPolygon,
    stemPathD: polygonToPath(stemPolygon),
    leaves: placeBrush(curve, { ...params.brush, taperStart: params.taperStart, taperEnd: params.taperEnd }),
  };
}

/** Forme persistable d'une liane : juste assez pour la reconstruire (nœuds,
    liane parente éventuelle, paramètres utilisés) — tout le reste (curve,
    polygone, feuilles) est dérivé et se recalcule via regenerateVine(). */
export interface SerializedVine {
  id: string;
  nodes: EditableNode[];
  parentId?: string;
  params: VineParams;
}

/** Forme persistable de tout le canevas : les lianes, et la zone de travail (masque) éventuelle — voir mask.ts. */
export interface CanvasSnapshot {
  vines: SerializedVine[];
  mask: Point[] | null;
}

/** Sérialise tout le canevas (undo/redo comme sauvegarde locale utilisent le même format). */
export function serializeCanvas(
  vines: Map<string, { nodes: EditableNode[]; parentId?: string; params: VineParams }>,
  mask: Point[] | null,
): string {
  const list: SerializedVine[] = [...vines].map(([id, v]) => ({
    id,
    nodes: v.nodes,
    parentId: v.parentId,
    params: v.params,
  }));
  return JSON.stringify({ vines: list, mask });
}

function isPoint(v: unknown): v is Point {
  return typeof v === "object" && v !== null && typeof (v as Point).x === "number" && typeof (v as Point).y === "number";
}

function isEditableNode(v: unknown): v is EditableNode {
  if (typeof v !== "object" || v === null) return false;
  const n = v as EditableNode;
  return (
    isPoint(n.point) &&
    isPoint(n.handleIn) &&
    isPoint(n.handleOut) &&
    (n.corner === undefined || typeof n.corner === "boolean")
  );
}

function isSerializedVine(v: unknown): v is SerializedVine {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o.id === "string" &&
    Array.isArray(o.nodes) &&
    o.nodes.every(isEditableNode) &&
    (o.parentId === undefined || typeof o.parentId === "string") &&
    typeof o.params === "object" &&
    o.params !== null
  );
}

function isMask(v: unknown): v is Point[] | null {
  return v === null || (Array.isArray(v) && v.every(isPoint));
}

function isCanvasSnapshot(v: unknown): v is CanvasSnapshot {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return Array.isArray(o.vines) && o.vines.every(isSerializedVine) && isMask(o.mask);
}

/**
 * Désérialise un instantané en validant sa forme — une chaîne corrompue,
 * vide ou d'un format incompatible (schéma antérieur, donnée altérée) donne
 * `null` plutôt que d'exploser plus loin dans le pipeline de régénération,
 * pour qu'une sauvegarde locale invalide ne puisse jamais bloquer le
 * démarrage de l'application.
 */
export function deserializeCanvas(json: string): CanvasSnapshot | null {
  try {
    const parsed: unknown = JSON.parse(json);
    if (!isCanvasSnapshot(parsed)) return null;
    return parsed;
  } catch {
    return null;
  }
}
